image: node:12.14.0

stages:
  - publish

publish:
  stage: publish
  when: manual
  script:
    - npm install -g lerna --registry https://registry.npm.taobao.org/
    - npm install --registry https://registry.npm.taobao.org/
    - npm config set //registry.npmjs.org/:_authToken ${AUTHING_ORG_NPM_TOKEN}
    - npm run publish:lib
    - echo "记得同步 taobao 源哦： https://npm.taobao.org/sync/@authing/ui-components  🚀"