image: node:12.14.0

stages:
  - build

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config

build:
  stage: build
  when: manual
  image:
    name: fuergaosi/ossutil:latest
  script:
    - yarn
    - yarn run build:lib
    - export VERSION=$(cat lerna.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - echo 上传包到 cdn
    - echo $CDN_OSS_PROD
    - echo $OSS_REGION_PROD
    - echo 版本 $VERSION
    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION_PROD} cp -r -f packages/angular-components/dist/bundles oss://${CDN_OSS_PROD}/packages/ng-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION_PROD} cp -r -f packages/native-js/lib oss://${CDN_OSS_PROD}/packages/native-js-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION_PROD} cp -r -f packages/react-components/lib oss://${CDN_OSS_PROD}/packages/react-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION_PROD} cp -r -f packages/vue-components/lib oss://${CDN_OSS_PROD}/packages/vue-ui-components/${VERSION}/
