image: node:12.14.0

stages:
  - build
  - upload

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config

build:
  stage: build
  when: manual
  script:
    - npm install --registry https://registry.npm.taobao.org/
    - npm run build
  artifacts:
    untracked: false
    paths:
      - packages/angular-components/dist
      - packages/native-js/lib
      - packages/react-components/lib
      - packages/vue-components/lib
    expire_in: 30 days

upload:
  stage: upload
  when: manual
  image:
    name: fuergaosi/ossutil:latest
  script:
    - export VERSION=$(cat lerna.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - echo 上传包到 cdn
    - echo $OSS_URL
    - echo $OSS_REGION
    - echo 版本 $VERSION
    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION} cp -r -f packages/angular-components/dist/bundles oss://${OSS_URL}/packages/ng-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION} cp -r -f packages/native-js/lib oss://${OSS_URL}/packages/native-js-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION} cp -r -f packages/react-components/lib oss://${OSS_URL}/packages/react-ui-components/${VERSION}/

    - >
      ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION} cp -r -f packages/vue-components/lib oss://${OSS_URL}/packages/vue-ui-components/${VERSION}/
  dependencies:
    - build
