export interface List {
  [key: string]: string
}
export const COUNTRY_LIST_ZH: List = {
  CN: '中国',
  HK: '中国香港特别行政区',
  MO: '中国澳门特别行政区',
  TW: '中国台湾省',
  AL: '阿尔巴尼亚',
  DZ: '阿尔及利亚',
  AF: '阿富汗',
  AR: '阿根廷',
  AE: '阿拉伯联合酋长国',
  AW: '阿鲁巴',
  OM: '阿曼',
  AZ: '阿塞拜疆',
  EG: '埃及',
  ET: '埃塞俄比亚',
  IE: '爱尔兰',
  EE: '爱沙尼亚',
  AD: '安道尔',
  AO: '安哥拉',
  AI: '安圭拉',
  AG: '安提瓜和巴布达',
  AT: '奥地利',
  AX: '奥兰群岛',
  AU: '澳大利亚',
  BB: '巴巴多斯',
  PG: '巴布亚新几内亚',
  BS: '巴哈马',
  PK: '巴基斯坦',
  PY: '巴拉圭',
  PS: '巴勒斯坦领土',
  BH: '巴林',
  PA: '巴拿马',
  BR: '巴西',
  BY: '白俄罗斯',
  BM: '百慕大',
  BG: '保加利亚',
  MP: '北马里亚纳群岛',
  MK: '北马其顿',
  BJ: '贝宁',
  BE: '比利时',
  IS: '冰岛',
  PR: '波多黎各',
  PL: '波兰',
  BA: '波斯尼亚和黑塞哥维那',
  BO: '玻利维亚',
  BZ: '伯利兹',
  BW: '博茨瓦纳',
  BT: '不丹',
  BF: '布基纳法索',
  BI: '布隆迪',
  BV: '布韦岛',
  KP: '朝鲜',
  GQ: '赤道几内亚',
  DK: '丹麦',
  DE: '德国',
  TL: '东帝汶',
  TG: '多哥',
  DO: '多米尼加共和国',
  DM: '多米尼克',
  RU: '俄罗斯',
  EC: '厄瓜多尔',
  ER: '厄立特里亚',
  FR: '法国',
  FO: '法罗群岛',
  PF: '法属波利尼西亚',
  GF: '法属圭亚那',
  TF: '法属南部领地',
  MF: '法属圣马丁',
  VA: '梵蒂冈',
  PH: '菲律宾',
  FJ: '斐济',
  FI: '芬兰',
  CV: '佛得角',
  FK: '福克兰群岛',
  GM: '冈比亚',
  CG: '刚果（布）',
  CD: '刚果（金）',
  CO: '哥伦比亚',
  CR: '哥斯达黎加',
  GD: '格林纳达',
  GL: '格陵兰',
  GE: '格鲁吉亚',
  GG: '根西岛',
  CU: '古巴',
  GP: '瓜德罗普',
  GU: '关岛',
  GY: '圭亚那',
  KZ: '哈萨克斯坦',
  HT: '海地',
  KR: '韩国',
  NL: '荷兰',
  BQ: '荷属加勒比区',
  SX: '荷属圣马丁',
  HM: '赫德岛和麦克唐纳群岛',
  ME: '黑山',
  HN: '洪都拉斯',
  KI: '基里巴斯',
  DJ: '吉布提',
  KG: '吉尔吉斯斯坦',
  GN: '几内亚',
  GW: '几内亚比绍',
  CA: '加拿大',
  GH: '加纳',
  GA: '加蓬',
  KH: '柬埔寨',
  CZ: '捷克',
  ZW: '津巴布韦',
  CM: '喀麦隆',
  QA: '卡塔尔',
  KY: '开曼群岛',
  CC: '科科斯（基林）群岛',
  KM: '科摩罗',
  CI: '科特迪瓦',
  KW: '科威特',
  HR: '克罗地亚',
  KE: '肯尼亚',
  CK: '库克群岛',
  CW: '库拉索',
  LV: '拉脱维亚',
  LS: '莱索托',
  LA: '老挝',
  LB: '黎巴嫩',
  LT: '立陶宛',
  LR: '利比里亚',
  LY: '利比亚',
  LI: '列支敦士登',
  RE: '留尼汪',
  LU: '卢森堡',
  RW: '卢旺达',
  RO: '罗马尼亚',
  MG: '马达加斯加',
  IM: '马恩岛',
  MV: '马尔代夫',
  MT: '马耳他',
  MW: '马拉维',
  MY: '马来西亚',
  ML: '马里',
  MH: '马绍尔群岛',
  MQ: '马提尼克',
  YT: '马约特',
  MU: '毛里求斯',
  MR: '毛里塔尼亚',
  US: '美国',
  UM: '美国本土外小岛屿',
  AS: '美属萨摩亚',
  VI: '美属维尔京群岛',
  MN: '蒙古',
  MS: '蒙特塞拉特',
  BD: '孟加拉国',
  PE: '秘鲁',
  FM: '密克罗尼西亚',
  MM: '缅甸',
  MD: '摩尔多瓦',
  MA: '摩洛哥',
  MC: '摩纳哥',
  MZ: '莫桑比克',
  MX: '墨西哥',
  NA: '纳米比亚',
  ZA: '南非',
  AQ: '南极洲',
  GS: '南乔治亚和南桑威奇群岛',
  SS: '南苏丹',
  NR: '瑙鲁',
  NI: '尼加拉瓜',
  NP: '尼泊尔',
  NE: '尼日尔',
  NG: '尼日利亚',
  NU: '纽埃',
  NO: '挪威',
  NF: '诺福克岛',
  PW: '帕劳',
  PN: '皮特凯恩群岛',
  PT: '葡萄牙',
  JP: '日本',
  SE: '瑞典',
  CH: '瑞士',
  SV: '萨尔瓦多',
  WS: '萨摩亚',
  RS: '塞尔维亚',
  SL: '塞拉利昂',
  SN: '塞内加尔',
  CY: '塞浦路斯',
  SC: '塞舌尔',
  SA: '沙特阿拉伯',
  BL: '圣巴泰勒米',
  CX: '圣诞岛',
  ST: '圣多美和普林西比',
  SH: '圣赫勒拿',
  KN: '圣基茨和尼维斯',
  LC: '圣卢西亚',
  SM: '圣马力诺',
  PM: '圣皮埃尔和密克隆群岛',
  VC: '圣文森特和格林纳丁斯',
  LK: '斯里兰卡',
  SK: '斯洛伐克',
  SI: '斯洛文尼亚',
  SJ: '斯瓦尔巴和扬马延',
  SZ: '斯威士兰',
  SD: '苏丹',
  SR: '苏里南',
  SB: '所罗门群岛',
  SO: '索马里',
  TJ: '塔吉克斯坦',
  TH: '泰国',
  TZ: '坦桑尼亚',
  TO: '汤加',
  TC: '特克斯和凯科斯群岛',
  TT: '特立尼达和多巴哥',
  TN: '突尼斯',
  TV: '图瓦卢',
  TR: '土耳其',
  TM: '土库曼斯坦',
  TK: '托克劳',
  WF: '瓦利斯和富图纳',
  VU: '瓦努阿图',
  GT: '危地马拉',
  VE: '委内瑞拉',
  BN: '文莱',
  UG: '乌干达',
  UA: '乌克兰',
  UY: '乌拉圭',
  UZ: '乌兹别克斯坦',
  ES: '西班牙',
  EH: '西撒哈拉',
  GR: '希腊',
  SG: '新加坡',
  NC: '新喀里多尼亚',
  NZ: '新西兰',
  HU: '匈牙利',
  SY: '叙利亚',
  JM: '牙买加',
  AM: '亚美尼亚',
  YE: '也门',
  IQ: '伊拉克',
  IR: '伊朗',
  IL: '以色列',
  IT: '意大利',
  IN: '印度',
  ID: '印度尼西亚',
  GB: '英国',
  VG: '英属维尔京群岛',
  IO: '英属印度洋领地',
  JO: '约旦',
  VN: '越南',
  ZM: '赞比亚',
  JE: '泽西岛',
  TD: '乍得',
  GI: '直布罗陀',
  CL: '智利',
  CF: '中非共和国',
}

export const COUNTRY_LIST_EN: List = {
  CN: 'China',
  HK: 'Hong Kong SAR China',
  MO: 'Macao SAR China',
  TW: 'Taiwan',
  AF: 'Afghanistan',
  AX: 'Åland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua & Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia & Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  VG: 'British Virgin Islands',
  BN: 'Brunei',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  BQ: 'Caribbean Netherlands',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo - Brazzaville',
  CD: 'Congo - Kinshasa',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: 'Côte d’Ivoire',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  FK: 'Falkland Islands',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard & McDonald Islands',
  HN: 'Honduras',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Laos',
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar (Burma)',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  KP: 'North Korea',
  MK: 'North Macedonia',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territories',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn Islands',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RU: 'Russia',
  RW: 'Rwanda',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'São Tomé & Príncipe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia & South Sandwich Islands',
  KR: 'South Korea',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  BL: 'St. Barthélemy',
  SH: 'St. Helena',
  KN: 'St. Kitts & Nevis',
  LC: 'St. Lucia',
  MF: 'St. Martin',
  PM: 'St. Pierre & Miquelon',
  VC: 'St. Vincent & Grenadines',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard & Jan Mayen',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syria',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad & Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks & Caicos Islands',
  TV: 'Tuvalu',
  UM: 'U.S. Outlying Islands',
  VI: 'U.S. Virgin Islands',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VA: 'Vatican City',
  VE: 'Venezuela',
  VN: 'Vietnam',
  WF: 'Wallis & Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

export const Phone_List: List = {
  BD: '880',
  BE: '32',
  BF: '226',
  BG: '359',
  BA: '387',
  BB: '+1-246',
  WF: '681',
  BL: '590',
  BM: '+1-441',
  BN: '673',
  BO: '591',
  BH: '973',
  BI: '257',
  BJ: '229',
  BT: '975',
  JM: '+1-876',
  BV: '',
  BW: '267',
  WS: '685',
  BQ: '599',
  BR: '55',
  BS: '+1-242',
  JE: '+44-1534',
  BY: '375',
  BZ: '501',
  RU: '7',
  RW: '250',
  RS: '381',
  TL: '670',
  RE: '262',
  TM: '993',
  TJ: '992',
  RO: '40',
  TK: '690',
  GW: '245',
  GU: '+1-671',
  GT: '502',
  GS: '',
  GR: '30',
  GQ: '240',
  GP: '590',
  JP: '81',
  GY: '592',
  GG: '+44-1481',
  GF: '594',
  GE: '995',
  GD: '+1-473',
  GB: '44',
  GA: '241',
  SV: '503',
  GN: '224',
  GM: '220',
  GL: '299',
  GI: '350',
  GH: '233',
  OM: '968',
  TN: '216',
  JO: '962',
  HR: '385',
  HT: '509',
  HU: '36',
  HK: '852',
  HN: '504',
  HM: ' ',
  VE: '58',
  PR: '+1-787 and 1-939',
  PS: '970',
  PW: '680',
  PT: '351',
  SJ: '47',
  PY: '595',
  IQ: '964',
  PA: '507',
  PF: '689',
  PG: '675',
  PE: '51',
  PK: '92',
  PH: '63',
  PN: '870',
  PL: '48',
  PM: '508',
  ZM: '260',
  EH: '212',
  EE: '372',
  EG: '20',
  ZA: '27',
  EC: '593',
  IT: '39',
  VN: '84',
  SB: '677',
  ET: '251',
  SO: '252',
  ZW: '263',
  SA: '966',
  ES: '34',
  ER: '291',
  ME: '382',
  MD: '373',
  MG: '261',
  MF: '590',
  MA: '212',
  MC: '377',
  UZ: '998',
  MM: '95',
  ML: '223',
  MO: '853',
  MN: '976',
  MH: '692',
  MK: '389',
  MU: '230',
  MT: '356',
  MW: '265',
  MV: '960',
  MQ: '596',
  MP: '+1-670',
  MS: '+1-664',
  MR: '222',
  IM: '+44-1624',
  UG: '256',
  TZ: '255',
  MY: '60',
  MX: '52',
  IL: '972',
  FR: '33',
  IO: '246',
  SH: '290',
  FI: '358',
  FJ: '679',
  FK: '500',
  FM: '691',
  FO: '298',
  NI: '505',
  NL: '31',
  NO: '47',
  NA: '264',
  VU: '678',
  NC: '687',
  NE: '227',
  NF: '672',
  NG: '234',
  NZ: '64',
  NP: '977',
  NR: '674',
  NU: '683',
  CK: '682',
  XK: '',
  CI: '225',
  CH: '41',
  CO: '57',
  CN: '86',
  CM: '237',
  CL: '56',
  CC: '61',
  CA: '1',
  CG: '242',
  CF: '236',
  CD: '243',
  CZ: '420',
  CY: '357',
  CX: '61',
  CR: '506',
  CW: '599',
  CV: '238',
  CU: '53',
  SZ: '268',
  SY: '963',
  SX: '599',
  KG: '996',
  KE: '254',
  SS: '211',
  SR: '597',
  KI: '686',
  KH: '855',
  KN: '+1-869',
  KM: '269',
  ST: '239',
  SK: '421',
  KR: '82',
  SI: '386',
  KP: '850',
  KW: '965',
  SN: '221',
  SM: '378',
  SL: '232',
  SC: '248',
  KZ: '7',
  KY: '+1-345',
  SG: '65',
  SE: '46',
  SD: '249',
  DO: '+1-809 and 1-829',
  DM: '+1-767',
  DJ: '253',
  DK: '45',
  VG: '+1-284',
  DE: '49',
  YE: '967',
  DZ: '213',
  US: '1',
  UY: '598',
  YT: '262',
  UM: '1',
  LB: '961',
  LC: '+1-758',
  LA: '856',
  TV: '688',
  TW: '886',
  TT: '+1-868',
  TR: '90',
  LK: '94',
  LI: '423',
  LV: '371',
  TO: '676',
  LT: '370',
  LU: '352',
  LR: '231',
  LS: '266',
  TH: '66',
  TF: '',
  TG: '228',
  TD: '235',
  TC: '+1-649',
  LY: '218',
  VA: '379',
  VC: '+1-784',
  AE: '971',
  AD: '376',
  AG: '+1-268',
  AF: '93',
  AI: '+1-264',
  VI: '+1-340',
  IS: '354',
  IR: '98',
  AM: '374',
  AL: '355',
  AO: '244',
  AQ: '',
  AS: '+1-684',
  AR: '54',
  AU: '61',
  AT: '43',
  AW: '297',
  IN: '91',
  AX: '+358-18',
  AZ: '994',
  IE: '353',
  ID: '62',
  UA: '380',
  QA: '974',
  MZ: '258',
}
export interface Iso {
  iso: string
  regions: string
  regions_en: string
  areaCode: string
}
export const isoInfo: Iso[] = [
  {
    iso: 'CN',
    regions: '中国',
    regions_en: 'China',
    areaCode: '+86',
  },
  {
    iso: 'HK',
    regions: '中国香港特别行政区',
    regions_en: 'Hong Kong SAR China',
    areaCode: '+852',
  },
  {
    iso: 'MO',
    regions: '中国澳门特别行政区',
    regions_en: 'Macao SAR China',
    areaCode: '+853',
  },
  {
    iso: 'TW',
    regions: '中国台湾省',
    regions_en: 'Taiwan',
    areaCode: '+886',
  },
  {
    iso: 'AL',
    regions: '阿尔巴尼亚',
    regions_en: 'Albania',
    areaCode: '+355',
  },
  {
    iso: 'DZ',
    regions: '阿尔及利亚',
    regions_en: 'Algeria',
    areaCode: '+213',
  },
  {
    iso: 'AF',
    regions: '阿富汗',
    regions_en: 'Afghanistan',
    areaCode: '+93',
  },
  {
    iso: 'AR',
    regions: '阿根廷',
    regions_en: 'Argentina',
    areaCode: '+54',
  },
  {
    iso: 'AE',
    regions: '阿拉伯联合酋长国',
    regions_en: 'United Arab Emirates',
    areaCode: '+971',
  },
  {
    iso: 'AW',
    regions: '阿鲁巴',
    regions_en: 'Aruba',
    areaCode: '+297',
  },
  {
    iso: 'OM',
    regions: '阿曼',
    regions_en: 'Oman',
    areaCode: '+968',
  },
  {
    iso: 'AZ',
    regions: '阿塞拜疆',
    regions_en: 'Azerbaijan',
    areaCode: '+994',
  },
  {
    iso: 'EG',
    regions: '埃及',
    regions_en: 'Egypt',
    areaCode: '+20',
  },
  {
    iso: 'ET',
    regions: '埃塞俄比亚',
    regions_en: 'Ethiopia',
    areaCode: '+251',
  },
  {
    iso: 'IE',
    regions: '爱尔兰',
    regions_en: 'Ireland',
    areaCode: '+353',
  },
  {
    iso: 'EE',
    regions: '爱沙尼亚',
    regions_en: 'Estonia',
    areaCode: '+372',
  },
  {
    iso: 'AD',
    regions: '安道尔',
    regions_en: 'Andorra',
    areaCode: '+376',
  },
  {
    iso: 'AO',
    regions: '安哥拉',
    regions_en: 'Angola',
    areaCode: '+244',
  },
  {
    iso: 'AI',
    regions: '安圭拉',
    regions_en: 'Anguilla',
    areaCode: '+1-264',
  },
  {
    iso: 'AG',
    regions: '安提瓜和巴布达',
    regions_en: 'Antigua & Barbuda',
    areaCode: '+1-268',
  },
  {
    iso: 'AT',
    regions: '奥地利',
    regions_en: 'Austria',
    areaCode: '+43',
  },
  {
    iso: 'AX',
    regions: '奥兰群岛',
    regions_en: 'Åland Islands',
    areaCode: '+358-18',
  },
  {
    iso: 'AU',
    regions: '澳大利亚',
    regions_en: 'Australia',
    areaCode: '+61',
  },
  {
    iso: 'BB',
    regions: '巴巴多斯',
    regions_en: 'Barbados',
    areaCode: '+1-246',
  },
  {
    iso: 'PG',
    regions: '巴布亚新几内亚',
    regions_en: 'Papua New Guinea',
    areaCode: '+675',
  },
  {
    iso: 'BS',
    regions: '巴哈马',
    regions_en: 'Bahamas',
    areaCode: '+1-242',
  },
  {
    iso: 'PK',
    regions: '巴基斯坦',
    regions_en: 'Pakistan',
    areaCode: '+92',
  },
  {
    iso: 'PY',
    regions: '巴拉圭',
    regions_en: 'Paraguay',
    areaCode: '+595',
  },
  {
    iso: 'PS',
    regions: '巴勒斯坦领土',
    regions_en: 'Palestinian Territories',
    areaCode: '+970',
  },
  {
    iso: 'BH',
    regions: '巴林',
    regions_en: 'Bahrain',
    areaCode: '+973',
  },
  {
    iso: 'PA',
    regions: '巴拿马',
    regions_en: 'Panama',
    areaCode: '+507',
  },
  {
    iso: 'BR',
    regions: '巴西',
    regions_en: 'Brazil',
    areaCode: '+55',
  },
  {
    iso: 'BY',
    regions: '白俄罗斯',
    regions_en: 'Belarus',
    areaCode: '+375',
  },
  {
    iso: 'BM',
    regions: '百慕大',
    regions_en: 'Bermuda',
    areaCode: '+1-441',
  },
  {
    iso: 'BG',
    regions: '保加利亚',
    regions_en: 'Bulgaria',
    areaCode: '+359',
  },
  {
    iso: 'MP',
    regions: '北马里亚纳群岛',
    regions_en: 'Northern Mariana Islands',
    areaCode: '+1-670',
  },
  {
    iso: 'MK',
    regions: '北马其顿',
    regions_en: 'North Macedonia',
    areaCode: '+389',
  },
  {
    iso: 'BJ',
    regions: '贝宁',
    regions_en: 'Benin',
    areaCode: '+229',
  },
  {
    iso: 'BE',
    regions: '比利时',
    regions_en: 'Belgium',
    areaCode: '+32',
  },
  {
    iso: 'IS',
    regions: '冰岛',
    regions_en: 'Iceland',
    areaCode: '+354',
  },
  {
    iso: 'PR',
    regions: '波多黎各',
    regions_en: 'Puerto Rico',
    areaCode: '+1-787/939',
  },
  {
    iso: 'PL',
    regions: '波兰',
    regions_en: 'Poland',
    areaCode: '+48',
  },
  {
    iso: 'BA',
    regions: '波斯尼亚和黑塞哥维那',
    regions_en: 'Bosnia & Herzegovina',
    areaCode: '+387',
  },
  {
    iso: 'BO',
    regions: '玻利维亚',
    regions_en: 'Bolivia',
    areaCode: '+591',
  },
  {
    iso: 'BZ',
    regions: '伯利兹',
    regions_en: 'Belize',
    areaCode: '+501',
  },
  {
    iso: 'BW',
    regions: '博茨瓦纳',
    regions_en: 'Botswana',
    areaCode: '+267',
  },
  {
    iso: 'BT',
    regions: '不丹',
    regions_en: 'Bhutan',
    areaCode: '+975',
  },
  {
    iso: 'BF',
    regions: '布基纳法索',
    regions_en: 'Burkina Faso',
    areaCode: '+226',
  },
  {
    iso: 'BI',
    regions: '布隆迪',
    regions_en: 'Burundi',
    areaCode: '+257',
  },
  {
    iso: 'BV',
    regions: '布韦岛',
    regions_en: 'Bouvet Island',
    areaCode: '+',
  },
  {
    iso: 'KP',
    regions: '朝鲜',
    regions_en: 'North Korea',
    areaCode: '+850',
  },
  {
    iso: 'GQ',
    regions: '赤道几内亚',
    regions_en: 'Equatorial Guinea',
    areaCode: '+240',
  },
  {
    iso: 'DK',
    regions: '丹麦',
    regions_en: 'Denmark',
    areaCode: '+45',
  },
  {
    iso: 'DE',
    regions: '德国',
    regions_en: 'Germany',
    areaCode: '+49',
  },
  {
    iso: 'TL',
    regions: '东帝汶',
    regions_en: 'Timor-Leste',
    areaCode: '+670',
  },
  {
    iso: 'TG',
    regions: '多哥',
    regions_en: 'Togo',
    areaCode: '+228',
  },
  {
    iso: 'DO',
    regions: '多米尼加共和国',
    regions_en: 'Dominican Republic',
    areaCode: '+1-809 and 1-829',
  },
  {
    iso: 'DM',
    regions: '多米尼克',
    regions_en: 'Dominica',
    areaCode: '+1-767',
  },
  {
    iso: 'RU',
    regions: '俄罗斯',
    regions_en: 'Russia',
    areaCode: '+7',
  },
  {
    iso: 'EC',
    regions: '厄瓜多尔',
    regions_en: 'Ecuador',
    areaCode: '+593',
  },
  {
    iso: 'ER',
    regions: '厄立特里亚',
    regions_en: 'Eritrea',
    areaCode: '+291',
  },
  {
    iso: 'FR',
    regions: '法国',
    regions_en: 'France',
    areaCode: '+33',
  },
  {
    iso: 'FO',
    regions: '法罗群岛',
    regions_en: 'Faroe Islands',
    areaCode: '+298',
  },
  {
    iso: 'PF',
    regions: '法属波利尼西亚',
    regions_en: 'French Polynesia',
    areaCode: '+689',
  },
  {
    iso: 'GF',
    regions: '法属圭亚那',
    regions_en: 'French Guiana',
    areaCode: '+594',
  },
  {
    iso: 'TF',
    regions: '法属南部领地',
    regions_en: 'French Southern Territories',
    areaCode: '+',
  },
  {
    iso: 'MF',
    regions: '法属圣马丁',
    regions_en: 'St. Martin',
    areaCode: '+590',
  },
  {
    iso: 'VA',
    regions: '梵蒂冈',
    regions_en: 'Vatican City',
    areaCode: '+379',
  },
  {
    iso: 'PH',
    regions: '菲律宾',
    regions_en: 'Philippines',
    areaCode: '+63',
  },
  {
    iso: 'FJ',
    regions: '斐济',
    regions_en: 'Fiji',
    areaCode: '+679',
  },
  {
    iso: 'FI',
    regions: '芬兰',
    regions_en: 'Finland',
    areaCode: '+358',
  },
  {
    iso: 'CV',
    regions: '佛得角',
    regions_en: 'Cape Verde',
    areaCode: '+238',
  },
  {
    iso: 'FK',
    regions: '福克兰群岛',
    regions_en: 'Falkland Islands',
    areaCode: '+500',
  },
  {
    iso: 'GM',
    regions: '冈比亚',
    regions_en: 'Gambia',
    areaCode: '+220',
  },
  {
    iso: 'CG',
    regions: '刚果（布）',
    regions_en: 'Congo - Brazzaville',
    areaCode: '+242',
  },
  {
    iso: 'CD',
    regions: '刚果（金）',
    regions_en: 'Congo - Kinshasa',
    areaCode: '+243',
  },
  {
    iso: 'CO',
    regions: '哥伦比亚',
    regions_en: 'Colombia',
    areaCode: '+57',
  },
  {
    iso: 'CR',
    regions: '哥斯达黎加',
    regions_en: 'Costa Rica',
    areaCode: '+506',
  },
  {
    iso: 'GD',
    regions: '格林纳达',
    regions_en: 'Grenada',
    areaCode: '+1-473',
  },
  {
    iso: 'GL',
    regions: '格陵兰',
    regions_en: 'Greenland',
    areaCode: '+299',
  },
  {
    iso: 'GE',
    regions: '格鲁吉亚',
    regions_en: 'Georgia',
    areaCode: '+995',
  },
  {
    iso: 'GG',
    regions: '根西岛',
    regions_en: 'Guernsey',
    areaCode: '+44-1481',
  },
  {
    iso: 'CU',
    regions: '古巴',
    regions_en: 'Cuba',
    areaCode: '+53',
  },
  {
    iso: 'GP',
    regions: '瓜德罗普',
    regions_en: 'Guadeloupe',
    areaCode: '+590',
  },
  {
    iso: 'GU',
    regions: '关岛',
    regions_en: 'Guam',
    areaCode: '+1-671',
  },
  {
    iso: 'GY',
    regions: '圭亚那',
    regions_en: 'Guyana',
    areaCode: '+592',
  },
  {
    iso: 'KZ',
    regions: '哈萨克斯坦',
    regions_en: 'Kazakhstan',
    areaCode: '+7',
  },
  {
    iso: 'HT',
    regions: '海地',
    regions_en: 'Haiti',
    areaCode: '+509',
  },
  {
    iso: 'KR',
    regions: '韩国',
    regions_en: 'South Korea',
    areaCode: '+82',
  },
  {
    iso: 'NL',
    regions: '荷兰',
    regions_en: 'Netherlands',
    areaCode: '+31',
  },
  {
    iso: 'BQ',
    regions: '荷属加勒比区',
    regions_en: 'Caribbean Netherlands',
    areaCode: '+599',
  },
  {
    iso: 'SX',
    regions: '荷属圣马丁',
    regions_en: 'Sint Maarten',
    areaCode: '+599',
  },
  {
    iso: 'HM',
    regions: '赫德岛和麦克唐纳群岛',
    regions_en: 'Heard & McDonald Islands',
    areaCode: '+ ',
  },
  {
    iso: 'ME',
    regions: '黑山',
    regions_en: 'Montenegro',
    areaCode: '+382',
  },
  {
    iso: 'HN',
    regions: '洪都拉斯',
    regions_en: 'Honduras',
    areaCode: '+504',
  },
  {
    iso: 'KI',
    regions: '基里巴斯',
    regions_en: 'Kiribati',
    areaCode: '+686',
  },
  {
    iso: 'DJ',
    regions: '吉布提',
    regions_en: 'Djibouti',
    areaCode: '+253',
  },
  {
    iso: 'KG',
    regions: '吉尔吉斯斯坦',
    regions_en: 'Kyrgyzstan',
    areaCode: '+996',
  },
  {
    iso: 'GN',
    regions: '几内亚',
    regions_en: 'Guinea',
    areaCode: '+224',
  },
  {
    iso: 'GW',
    regions: '几内亚比绍',
    regions_en: 'Guinea-Bissau',
    areaCode: '+245',
  },
  {
    iso: 'CA',
    regions: '加拿大',
    regions_en: 'Canada',
    areaCode: '+1',
  },
  {
    iso: 'GH',
    regions: '加纳',
    regions_en: 'Ghana',
    areaCode: '+233',
  },
  {
    iso: 'GA',
    regions: '加蓬',
    regions_en: 'Gabon',
    areaCode: '+241',
  },
  {
    iso: 'KH',
    regions: '柬埔寨',
    regions_en: 'Cambodia',
    areaCode: '+855',
  },
  {
    iso: 'CZ',
    regions: '捷克',
    regions_en: 'Czechia',
    areaCode: '+420',
  },
  {
    iso: 'ZW',
    regions: '津巴布韦',
    regions_en: 'Zimbabwe',
    areaCode: '+263',
  },
  {
    iso: 'CM',
    regions: '喀麦隆',
    regions_en: 'Cameroon',
    areaCode: '+237',
  },
  {
    iso: 'QA',
    regions: '卡塔尔',
    regions_en: 'Qatar',
    areaCode: '+974',
  },
  {
    iso: 'KY',
    regions: '开曼群岛',
    regions_en: 'Cayman Islands',
    areaCode: '+1-345',
  },
  {
    iso: 'CC',
    regions: '科科斯（基林）群岛',
    regions_en: 'Cocos (Keeling) Islands',
    areaCode: '+61',
  },
  {
    iso: 'KM',
    regions: '科摩罗',
    regions_en: 'Comoros',
    areaCode: '+269',
  },
  {
    iso: 'CI',
    regions: '科特迪瓦',
    regions_en: 'Côte d’Ivoire',
    areaCode: '+225',
  },
  {
    iso: 'KW',
    regions: '科威特',
    regions_en: 'Kuwait',
    areaCode: '+965',
  },
  {
    iso: 'HR',
    regions: '克罗地亚',
    regions_en: 'Croatia',
    areaCode: '+385',
  },
  {
    iso: 'KE',
    regions: '肯尼亚',
    regions_en: 'Kenya',
    areaCode: '+254',
  },
  {
    iso: 'CK',
    regions: '库克群岛',
    regions_en: 'Cook Islands',
    areaCode: '+682',
  },
  {
    iso: 'CW',
    regions: '库拉索',
    regions_en: 'Curaçao',
    areaCode: '+599',
  },
  {
    iso: 'LV',
    regions: '拉脱维亚',
    regions_en: 'Latvia',
    areaCode: '+371',
  },
  {
    iso: 'LS',
    regions: '莱索托',
    regions_en: 'Lesotho',
    areaCode: '+266',
  },
  {
    iso: 'LA',
    regions: '老挝',
    regions_en: 'Laos',
    areaCode: '+856',
  },
  {
    iso: 'LB',
    regions: '黎巴嫩',
    regions_en: 'Lebanon',
    areaCode: '+961',
  },
  {
    iso: 'LT',
    regions: '立陶宛',
    regions_en: 'Lithuania',
    areaCode: '+370',
  },
  {
    iso: 'LR',
    regions: '利比里亚',
    regions_en: 'Liberia',
    areaCode: '+231',
  },
  {
    iso: 'LY',
    regions: '利比亚',
    regions_en: 'Libya',
    areaCode: '+218',
  },
  {
    iso: 'LI',
    regions: '列支敦士登',
    regions_en: 'Liechtenstein',
    areaCode: '+423',
  },
  {
    iso: 'RE',
    regions: '留尼汪',
    regions_en: 'Réunion',
    areaCode: '+262',
  },
  {
    iso: 'LU',
    regions: '卢森堡',
    regions_en: 'Luxembourg',
    areaCode: '+352',
  },
  {
    iso: 'RW',
    regions: '卢旺达',
    regions_en: 'Rwanda',
    areaCode: '+250',
  },
  {
    iso: 'RO',
    regions: '罗马尼亚',
    regions_en: 'Romania',
    areaCode: '+40',
  },
  {
    iso: 'MG',
    regions: '马达加斯加',
    regions_en: 'Madagascar',
    areaCode: '+261',
  },
  {
    iso: 'IM',
    regions: '马恩岛',
    regions_en: 'Isle of Man',
    areaCode: '+44-1624',
  },
  {
    iso: 'MV',
    regions: '马尔代夫',
    regions_en: 'Maldives',
    areaCode: '+960',
  },
  {
    iso: 'MT',
    regions: '马耳他',
    regions_en: 'Malta',
    areaCode: '+356',
  },
  {
    iso: 'MW',
    regions: '马拉维',
    regions_en: 'Malawi',
    areaCode: '+265',
  },
  {
    iso: 'MY',
    regions: '马来西亚',
    regions_en: 'Malaysia',
    areaCode: '+60',
  },
  {
    iso: 'ML',
    regions: '马里',
    regions_en: 'Mali',
    areaCode: '+223',
  },
  {
    iso: 'MH',
    regions: '马绍尔群岛',
    regions_en: 'Marshall Islands',
    areaCode: '+692',
  },
  {
    iso: 'MQ',
    regions: '马提尼克',
    regions_en: 'Martinique',
    areaCode: '+596',
  },
  {
    iso: 'YT',
    regions: '马约特',
    regions_en: 'Mayotte',
    areaCode: '+262',
  },
  {
    iso: 'MU',
    regions: '毛里求斯',
    regions_en: 'Mauritius',
    areaCode: '+230',
  },
  {
    iso: 'MR',
    regions: '毛里塔尼亚',
    regions_en: 'Mauritania',
    areaCode: '+222',
  },
  {
    iso: 'US',
    regions: '美国',
    regions_en: 'United States',
    areaCode: '+1',
  },
  {
    iso: 'AS',
    regions: '美属萨摩亚',
    regions_en: 'American Samoa',
    areaCode: '+1-684',
  },
  {
    iso: 'VI',
    regions: '美属维尔京群岛',
    regions_en: 'U.S. Virgin Islands',
    areaCode: '+1-340',
  },
  {
    iso: 'MN',
    regions: '蒙古',
    regions_en: 'Mongolia',
    areaCode: '+976',
  },
  {
    iso: 'MS',
    regions: '蒙特塞拉特',
    regions_en: 'Montserrat',
    areaCode: '+1-664',
  },
  {
    iso: 'BD',
    regions: '孟加拉国',
    regions_en: 'Bangladesh',
    areaCode: '+880',
  },
  {
    iso: 'PE',
    regions: '秘鲁',
    regions_en: 'Peru',
    areaCode: '+51',
  },
  {
    iso: 'FM',
    regions: '密克罗尼西亚',
    regions_en: 'Micronesia',
    areaCode: '+691',
  },
  {
    iso: 'MM',
    regions: '缅甸',
    regions_en: 'Myanmar (Burma)',
    areaCode: '+95',
  },
  {
    iso: 'MD',
    regions: '摩尔多瓦',
    regions_en: 'Moldova',
    areaCode: '+373',
  },
  {
    iso: 'MA',
    regions: '摩洛哥',
    regions_en: 'Morocco',
    areaCode: '+212',
  },
  {
    iso: 'MC',
    regions: '摩纳哥',
    regions_en: 'Monaco',
    areaCode: '+377',
  },
  {
    iso: 'MZ',
    regions: '莫桑比克',
    regions_en: 'Mozambique',
    areaCode: '+258',
  },
  {
    iso: 'MX',
    regions: '墨西哥',
    regions_en: 'Mexico',
    areaCode: '+52',
  },
  {
    iso: 'NA',
    regions: '纳米比亚',
    regions_en: 'Namibia',
    areaCode: '+264',
  },
  {
    iso: 'ZA',
    regions: '南非',
    regions_en: 'South Africa',
    areaCode: '+27',
  },
  {
    iso: 'SS',
    regions: '南苏丹',
    regions_en: 'South Sudan',
    areaCode: '+211',
  },
  {
    iso: 'NR',
    regions: '瑙鲁',
    regions_en: 'Nauru',
    areaCode: '+674',
  },
  {
    iso: 'NI',
    regions: '尼加拉瓜',
    regions_en: 'Nicaragua',
    areaCode: '+505',
  },
  {
    iso: 'NP',
    regions: '尼泊尔',
    regions_en: 'Nepal',
    areaCode: '+977',
  },
  {
    iso: 'NE',
    regions: '尼日尔',
    regions_en: 'Niger',
    areaCode: '+227',
  },
  {
    iso: 'NG',
    regions: '尼日利亚',
    regions_en: 'Nigeria',
    areaCode: '+234',
  },
  {
    iso: 'NU',
    regions: '纽埃',
    regions_en: 'Niue',
    areaCode: '+683',
  },
  {
    iso: 'NO',
    regions: '挪威',
    regions_en: 'Norway',
    areaCode: '+47',
  },
  {
    iso: 'NF',
    regions: '诺福克岛',
    regions_en: 'Norfolk Island',
    areaCode: '+672',
  },
  {
    iso: 'PW',
    regions: '帕劳',
    regions_en: 'Palau',
    areaCode: '+680',
  },
  {
    iso: 'PN',
    regions: '皮特凯恩群岛',
    regions_en: 'Pitcairn Islands',
    areaCode: '+870',
  },
  {
    iso: 'PT',
    regions: '葡萄牙',
    regions_en: 'Portugal',
    areaCode: '+351',
  },
  {
    iso: 'JP',
    regions: '日本',
    regions_en: 'Japan',
    areaCode: '+81',
  },
  {
    iso: 'SE',
    regions: '瑞典',
    regions_en: 'Sweden',
    areaCode: '+46',
  },
  {
    iso: 'CH',
    regions: '瑞士',
    regions_en: 'Switzerland',
    areaCode: '+41',
  },
  {
    iso: 'SV',
    regions: '萨尔瓦多',
    regions_en: 'El Salvador',
    areaCode: '+503',
  },
  {
    iso: 'WS',
    regions: '萨摩亚',
    regions_en: 'Samoa',
    areaCode: '+685',
  },
  {
    iso: 'RS',
    regions: '塞尔维亚',
    regions_en: 'Serbia',
    areaCode: '+381',
  },
  {
    iso: 'SL',
    regions: '塞拉利昂',
    regions_en: 'Sierra Leone',
    areaCode: '+232',
  },
  {
    iso: 'SN',
    regions: '塞内加尔',
    regions_en: 'Senegal',
    areaCode: '+221',
  },
  {
    iso: 'CY',
    regions: '塞浦路斯',
    regions_en: 'Cyprus',
    areaCode: '+357',
  },
  {
    iso: 'SC',
    regions: '塞舌尔',
    regions_en: 'Seychelles',
    areaCode: '+248',
  },
  {
    iso: 'SA',
    regions: '沙特阿拉伯',
    regions_en: 'Saudi Arabia',
    areaCode: '+966',
  },
  {
    iso: 'BL',
    regions: '圣巴泰勒米',
    regions_en: 'St. Barthélemy',
    areaCode: '+590',
  },
  {
    iso: 'CX',
    regions: '圣诞岛',
    regions_en: 'Christmas Island',
    areaCode: '+61',
  },
  {
    iso: 'ST',
    regions: '圣多美和普林西比',
    regions_en: 'São Tomé & Príncipe',
    areaCode: '+239',
  },
  {
    iso: 'SH',
    regions: '圣赫勒拿',
    regions_en: 'St. Helena',
    areaCode: '+290',
  },
  {
    iso: 'KN',
    regions: '圣基茨和尼维斯',
    regions_en: 'St. Kitts & Nevis',
    areaCode: '+1-869',
  },
  {
    iso: 'LC',
    regions: '圣卢西亚',
    regions_en: 'St. Lucia',
    areaCode: '+1-758',
  },
  {
    iso: 'SM',
    regions: '圣马力诺',
    regions_en: 'San Marino',
    areaCode: '+378',
  },
  {
    iso: 'PM',
    regions: '圣皮埃尔和密克隆群岛',
    regions_en: 'St. Pierre & Miquelon',
    areaCode: '+508',
  },
  {
    iso: 'VC',
    regions: '圣文森特和格林纳丁斯',
    regions_en: 'St. Vincent & Grenadines',
    areaCode: '+1-784',
  },
  {
    iso: 'LK',
    regions: '斯里兰卡',
    regions_en: 'Sri Lanka',
    areaCode: '+94',
  },
  {
    iso: 'SK',
    regions: '斯洛伐克',
    regions_en: 'Slovakia',
    areaCode: '+421',
  },
  {
    iso: 'SI',
    regions: '斯洛文尼亚',
    regions_en: 'Slovenia',
    areaCode: '+386',
  },
  {
    iso: 'SJ',
    regions: '斯瓦尔巴和扬马延',
    regions_en: 'Svalbard & Jan Mayen',
    areaCode: '+47',
  },
  {
    iso: 'SZ',
    regions: '斯威士兰',
    regions_en: 'Eswatini',
    areaCode: '+268',
  },
  {
    iso: 'SD',
    regions: '苏丹',
    regions_en: 'Sudan',
    areaCode: '+249',
  },
  {
    iso: 'SR',
    regions: '苏里南',
    regions_en: 'Suriname',
    areaCode: '+597',
  },
  {
    iso: 'SB',
    regions: '所罗门群岛',
    regions_en: 'Solomon Islands',
    areaCode: '+677',
  },
  {
    iso: 'SO',
    regions: '索马里',
    regions_en: 'Somalia',
    areaCode: '+252',
  },
  {
    iso: 'TJ',
    regions: '塔吉克斯坦',
    regions_en: 'Tajikistan',
    areaCode: '+992',
  },
  {
    iso: 'TH',
    regions: '泰国',
    regions_en: 'Thailand',
    areaCode: '+66',
  },
  {
    iso: 'TZ',
    regions: '坦桑尼亚',
    regions_en: 'Tanzania',
    areaCode: '+255',
  },
  {
    iso: 'TO',
    regions: '汤加',
    regions_en: 'Tonga',
    areaCode: '+676',
  },
  {
    iso: 'TC',
    regions: '特克斯和凯科斯群岛',
    regions_en: 'Turks & Caicos Islands',
    areaCode: '+1-649',
  },
  {
    iso: 'TT',
    regions: '特立尼达和多巴哥',
    regions_en: 'Trinidad & Tobago',
    areaCode: '+1-868',
  },
  {
    iso: 'TN',
    regions: '突尼斯',
    regions_en: 'Tunisia',
    areaCode: '+216',
  },
  {
    iso: 'TV',
    regions: '图瓦卢',
    regions_en: 'Tuvalu',
    areaCode: '+688',
  },
  {
    iso: 'TR',
    regions: '土耳其',
    regions_en: 'Turkey',
    areaCode: '+90',
  },
  {
    iso: 'TM',
    regions: '土库曼斯坦',
    regions_en: 'Turkmenistan',
    areaCode: '+993',
  },
  {
    iso: 'TK',
    regions: '托克劳',
    regions_en: 'Tokelau',
    areaCode: '+690',
  },
  {
    iso: 'WF',
    regions: '瓦利斯和富图纳',
    regions_en: 'Wallis & Futuna',
    areaCode: '+681',
  },
  {
    iso: 'VU',
    regions: '瓦努阿图',
    regions_en: 'Vanuatu',
    areaCode: '+678',
  },
  {
    iso: 'GT',
    regions: '危地马拉',
    regions_en: 'Guatemala',
    areaCode: '+502',
  },
  {
    iso: 'VE',
    regions: '委内瑞拉',
    regions_en: 'Venezuela',
    areaCode: '+58',
  },
  {
    iso: 'BN',
    regions: '文莱',
    regions_en: 'Brunei',
    areaCode: '+673',
  },
  {
    iso: 'UG',
    regions: '乌干达',
    regions_en: 'Uganda',
    areaCode: '+256',
  },
  {
    iso: 'UA',
    regions: '乌克兰',
    regions_en: 'Ukraine',
    areaCode: '+380',
  },
  {
    iso: 'UY',
    regions: '乌拉圭',
    regions_en: 'Uruguay',
    areaCode: '+598',
  },
  {
    iso: 'UZ',
    regions: '乌兹别克斯坦',
    regions_en: 'Uzbekistan',
    areaCode: '+998',
  },
  {
    iso: 'ES',
    regions: '西班牙',
    regions_en: 'Spain',
    areaCode: '+34',
  },
  {
    iso: 'EH',
    regions: '西撒哈拉',
    regions_en: 'Western Sahara',
    areaCode: '+212',
  },
  {
    iso: 'GR',
    regions: '希腊',
    regions_en: 'Greece',
    areaCode: '+30',
  },
  {
    iso: 'SG',
    regions: '新加坡',
    regions_en: 'Singapore',
    areaCode: '+65',
  },
  {
    iso: 'NC',
    regions: '新喀里多尼亚',
    regions_en: 'New Caledonia',
    areaCode: '+687',
  },
  {
    iso: 'NZ',
    regions: '新西兰',
    regions_en: 'New Zealand',
    areaCode: '+64',
  },
  {
    iso: 'HU',
    regions: '匈牙利',
    regions_en: 'Hungary',
    areaCode: '+36',
  },
  {
    iso: 'SY',
    regions: '叙利亚',
    regions_en: 'Syria',
    areaCode: '+963',
  },
  {
    iso: 'JM',
    regions: '牙买加',
    regions_en: 'Jamaica',
    areaCode: '+1-876',
  },
  {
    iso: 'AM',
    regions: '亚美尼亚',
    regions_en: 'Armenia',
    areaCode: '+374',
  },
  {
    iso: 'YE',
    regions: '也门',
    regions_en: 'Yemen',
    areaCode: '+967',
  },
  {
    iso: 'IQ',
    regions: '伊拉克',
    regions_en: 'Iraq',
    areaCode: '+964',
  },
  {
    iso: 'IR',
    regions: '伊朗',
    regions_en: 'Iran',
    areaCode: '+98',
  },
  {
    iso: 'IL',
    regions: '以色列',
    regions_en: 'Israel',
    areaCode: '+972',
  },
  {
    iso: 'IT',
    regions: '意大利',
    regions_en: 'Italy',
    areaCode: '+39',
  },
  {
    iso: 'IN',
    regions: '印度',
    regions_en: 'India',
    areaCode: '+91',
  },
  {
    iso: 'ID',
    regions: '印度尼西亚',
    regions_en: 'Indonesia',
    areaCode: '+62',
  },
  {
    iso: 'GB',
    regions: '英国',
    regions_en: 'United Kingdom',
    areaCode: '+44',
  },
  {
    iso: 'VG',
    regions: '英属维尔京群岛',
    regions_en: 'British Virgin Islands',
    areaCode: '+1-284',
  },
  {
    iso: 'IO',
    regions: '英属印度洋领地',
    regions_en: 'British Indian Ocean Territory',
    areaCode: '+246',
  },
  {
    iso: 'JO',
    regions: '约旦',
    regions_en: 'Jordan',
    areaCode: '+962',
  },
  {
    iso: 'VN',
    regions: '越南',
    regions_en: 'Vietnam',
    areaCode: '+84',
  },
  {
    iso: 'ZM',
    regions: '赞比亚',
    regions_en: 'Zambia',
    areaCode: '+260',
  },
  {
    iso: 'JE',
    regions: '泽西岛',
    regions_en: 'Jersey',
    areaCode: '+44-1534',
  },
  {
    iso: 'TD',
    regions: '乍得',
    regions_en: 'Chad',
    areaCode: '+235',
  },
  {
    iso: 'GI',
    regions: '直布罗陀',
    regions_en: 'Gibraltar',
    areaCode: '+350',
  },
  {
    iso: 'CL',
    regions: '智利',
    regions_en: 'Chile',
    areaCode: '+56',
  },
  {
    iso: 'CF',
    regions: '中非共和国',
    regions_en: 'Central African Republic',
    areaCode: '+236',
  },
]
