#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pwd

cd ./packages/react-components

yarn build:lib

cd -
cd ./packages/native-js

yarn build:lib

ls ./lib

ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
      --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
      -e ${OSS_REGION_PROD} cp -r -f packages/angular-components/dist/ng-ui-components/bundles oss://${CDN_OSS_PROD}/packages/ng-ui-components/${VERSION}/

